
blank_issues_enabled: true
contact_links:
  - name: Feature request
    url: https://github.com/lenra-io/dofigen/discussions/categories/ideas
    about: Please send your feature request in the discussion tab !
